### ISSUE TITLE
Not switching automatically to next song.

### ISSUE THREAD

**Issue by ayushhurdey** [ayu8/Music-Player#1]
Awesome work bro !! 👍 and nice collection of songs.🙂

But i was listening to the song and it was not switching to the next song automatically(Firefox browser).
Hope you will fix that.

**Comment by ayu8** [comment]
Hey thanks!
Actually I planned to make it in such a way that the song won't switch to next, upon completion of the current song, automatically and the listener will have to turn on "Loop" for the purpose but as now many people are asking of auto-switching to be the default option, I will change that accordingly.
